/* ============================================================================
   Neurodiverz profil-szűrő — kérdésbank
   Forrás: ~/Documents/neurodiverz-kutatas (14 állapot jegyzet.md + teszt-terv.md)
   FIGYELEM: tájékoztatási/önismereti eszköz, NEM diagnosztikai teszt.
   Pontozás: minden item 0–4 (Egyáltalán nem … Teljesen jellemző), magasabb = erősebb jelzés.
   ============================================================================ */

/* Állapot-meta: kód, név, rövid leírás, szín, formális-diagnózis-e */
const CONDITIONS = [
  { c:"adhd", name:"ADHD", full:"Figyelemhiányos hiperaktivitás-zavar", color:"#ef4444", formal:true, cutoff:56, cutoffNote:"ASRS-5 (Ustun 2017): ≥14/25 ≈ 56%. Szenzitivitás 91% / specificitás 96%.",
    desc:"A figyelem, a végrehajtó funkciók és/vagy a hiperaktivitás-impulzivitás tartós, a mindennapokat befolyásoló eltérése." },
  { c:"asd", name:"Autizmus (ASD)", full:"Autizmus spektrum", color:"#6366f1", formal:true, cutoff:60, cutoffNote:"AQ-10 (Allison 2012, NICE-ajánlott gyorsszűrő): ≥6/10 ≈ 60%. Szenz. 88% / spec. 91%. (Bináris eredeti → durvább átvitel; a RAADS-R alacsonyabb, érzékenyebb küszöböt ad.)",
    desc:"Eltérő szociális kommunikáció, repetitív viselkedés/szűk érdeklődés és gyakori szenzoros érzékenység." },
  { c:"diszlexia", name:"Diszlexia", full:"Olvasászavar", color:"#f59e0b", formal:true, cutoff:40, cutoffNote:"ARHQ (Lefly & Pennington 2000): ≥0,40 arány ≈ 40%. Szenz. 82% / spec. 78%.",
    desc:"Az olvasás pontosságának/folyékonyságának és a helyesírásnak az általános képességhez mért elmaradása." },
  { c:"diszkalkulia", name:"Diszkalkulia", full:"Számolászavar", color:"#10b981", formal:true, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"A számérzék, az aritmetikai tények és a számolási folyékonyság specifikus nehézsége." },
  { c:"diszgrafia", name:"Diszgráfia", full:"Írászavar", color:"#14b8a6", formal:true, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"A kézírás és/vagy az írásbeli kifejezés motoros és ortográfiai nehézsége." },
  { c:"dcd", name:"Diszpraxia (DCD)", full:"Fejlődési koordinációs zavar", color:"#0ea5e9", formal:true, cutoff:47, cutoffNote:"ADC (Kirby 2010): ≥56 „kockázat” ≈ 47% (≥65 „valószínű DCD” ≈ 54%).",
    desc:"A motoros koordináció és a mozgástervezés (praxis) az életkorhoz mért feltűnő nehézsége." },
  { c:"tourette", name:"Tourette / tic", full:"Tourette-szindróma és tic-zavarok", color:"#8b5cf6", formal:true, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"Akaratlan, ismétlődő motoros és/vagy vokális tic-ek, gyakran megelőző (premonitórikus) feszültséggel." },
  { c:"ocd", name:"OCD", full:"Kényszerbetegség", color:"#ec4899", formal:true, cutoff:29, cutoffNote:"OCI-R (Foa 2002): ≥21/72 ≈ 29%. Validált klinikai cutoff; azonos 0–4 Likert-formátum, ezért jól átvihető.",
    desc:"Visszatérő, nemkívánt gondolatok (obszessziók) és szorongáscsökkentő ismétlő cselekvések (kompulziók)." },
  { c:"spd", name:"Szenzoros (SPD)", full:"Szenzoros feldolgozási zavar", color:"#f97316", formal:false, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"Az érzékszervi ingerek szokatlan feldolgozása (túl- vagy alulérzékenység, ingerkeresés). Nem önálló diagnózis." },
  { c:"dld", name:"Nyelvi zavar (DLD)", full:"Fejlődési nyelvi zavar", color:"#84cc16", formal:true, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"A beszélt nyelv (szókincs, grammatika, megértés, elbeszélés) tartós, az értelmi szinttől független nehézsége." },
  { c:"pda", name:"PDA", full:"Patológiás igény-elkerülés", color:"#a855f7", formal:false, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"Az elvárások szorongás-vezérelt, szélsőséges elkerülése — vitatott konstruktum, gyakran az autizmus-profil része." },
  { c:"hiperlexia", name:"Hiperlexia", full:"Hiperlexia", color:"#eab308", formal:false, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"Korai, önjáró szóolvasás a szövegértés elmaradása mellett; jellemzően autizmushoz társul. Nem önálló diagnózis." },
  { c:"mizofonia", name:"Mizofónia", full:"Mizofónia", color:"#06b6d4", formal:false, cutoff:87, cutoffNote:"MisoQuest (Siepsiak 2020): ≥61/70 ≈ 87%. (Az S-Five eltérő skálán ~35%-ot ad.)",
    desc:"Bizonyos (gyakran emberi) hangokra adott aránytalan düh/undor és menekülési késztetés." },
  { c:"te", name:"Kétszeresen kivételes", full:"Twice-exceptional (2e)", color:"#64748b", formal:false, cutoff:null, cutoffNote:"Nincs validált felnőtt önszűrő küszöb a szakirodalomban — az érték csak tájékozódásra.",
    desc:"Tehetség és egy (vagy több) tanulási/figyelmi eltérés együtt — a kettő kölcsönösen elfedheti egymást. Nem diagnózis." },
];

/* Domén-meta a másodlagos (domén) radarhoz */
const DOMAINS = {
  FIG:   "Figyelem / végrehajtó funkció",
  IMP:   "Impulzivitás / hiperaktivitás",
  SZOC:  "Szociális kommunikáció",
  SZENZ: "Szenzoros feldolgozás",
  MOT:   "Motoros koordináció",
  NYELV: "Nyelv / beszéd",
  TAN:   "Tanulás (olvasás/írás/számolás)",
  RIT:   "Repetitív / ritualisztikus",
  ERZ:   "Érzelmi szabályozás / szorongás",
  IGE:   "Igény-elkerülés / autonómia",
};

/* Itemek: id, c=állapot, d=domén, self=felnőtt/serdülő, proxy=gyermekről szülőként, g=forrás-alap, rev=fordított pontozású (opc.) */
const ITEMS = [
  // ADHD (adhd)
  { id:"adhd1", c:"adhd", d:"FIG", self:"A munkám vagy a tanulmányaim során, miután egy feladat nehéz részén túljutok, gyakran nehezemre esik befejezni az utolsó, apró részleteket, ezért a dolgaim félkészen maradnak.", proxy:"A gyermek a feladatok izgalmas vagy könnyű részét megcsinálja, de az utolsó lépéseket (befejezés, ellenőrzés, eltevés) rendszeresen félbehagyja, így a munkái befejezetlenül maradnak.", g:"ASRS v1.1 A1 tétel: 'trouble wrapping up the final details of a project, once the challenging parts have been done'" },
  { id:"adhd2", c:"adhd", d:"FIG", self:"A mindennapokban gyakran elfelejtek megbeszélt időpontokat, határidőket vagy elintézendő ügyeket, hacsak nem emlékeztet rá valami vagy valaki.", proxy:"A gyermek gyakran elfelejti a rábízott teendőket és a megbeszélt dolgokat (pl. mit kell hazavinnie, mire kell készülnie), külön emlékeztetés nélkül kiesik a fejéből.", g:"ASRS v1.1 A3 tétel: 'problems remembering appointments or obligations'; DSM-5-TR figyelmetlenség 'forgetful in daily activities'" },
  { id:"adhd3", c:"adhd", d:"FIG", self:"Zajos, mozgalmas környezetben is könnyen és tartósan a feladatomra tudok koncentrálni; a körülöttem lévő ingerek nemigen terelnek el.", proxy:"A gyermek zajos, mozgalmas környezetben is jól, tartósan oda tud figyelni; a körülötte zajló dolgok nemigen terelik el.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. ASRS v1.1 B11 tétel: 'distracted by activity or noise around you'; DSM-5-TR 'easily distracted'", rev:true },
  { id:"adhd4", c:"adhd", d:"FIG", self:"Gyakran másokra (partnerre, kollégára, emlékeztető appokra) támaszkodom, hogy az életem és a részleteim rendben maradjanak, mert magamtól nehezen tartom kézben őket.", proxy:"A gyermek életének rendben tartásához tartós felnőtt-támogatás kell (mások emlékeztetik, pakolnak helyette, terelik), egyedül a saját dolgait és a részleteket nem tudja kézben tartani.", g:"ASRS-5 (DSM-5) 6. tétel: 'depend on others to keep your life in order and attend to details'" },
  { id:"adhd5", c:"adhd", d:"IMP", self:"Még akkor is, amikor lehetne pihennem és lenne időm magamra, nehezen lazítok el és kapcsolok ki, mintha egy belső motor folyamatosan hajtana.", proxy:"A gyermek akkor sem tud igazán megnyugodni és csendben elfoglalni magát, amikor lehetne pihennie; mintha állandóan 'fel lenne pörögve', folyamatosan tevékenykedik.", g:"ASRS v1.1 A6 + B14 tétel: 'driven by a motor' / 'difficulty unwinding and relaxing when you have time to yourself'" },
  { id:"adhd6", c:"adhd", d:"IMP", self:"Beszélgetés közben gyakran a másik szavába vágok vagy befejezem helyette a mondatát, mielőtt ő végezne, illetve nehezemre esik kivárni, amíg sorra kerülök.", proxy:"A gyermek a beszélgetésbe vagy játékba gyakran beleszól, közbevág, kimondja a választ a kérdés vége előtt, és nehezen várja ki, amíg sorra kerül.", g:"ASRS v1.1 B16 + B17 tétel: 'finishing the sentences of the people you are talking to' / 'difficulty awaiting turn'" },
  { id:"adhd7", c:"adhd", d:"IMP", self:"Társas helyzetekben gyakran azt veszem észre, hogy túl sokat és túl gyorsan beszélek, témáról témára ugrom, és nehezen állok meg.", proxy:"A gyermek társas helyzetekben feltűnően sokat és gyorsan beszél, egyik témáról a másikra ugrik, és nehezen hagyja abba akkor is, ha kérik rá.", g:"ASRS v1.1 B15 tétel: 'talking too much when you are in social situations'; DSM-5-TR 'talks excessively'" },
  { id:"adhd8", c:"adhd", d:"ERZ", self:"Egy apró bosszúság vagy frusztráció a vártnál hevesebb indulatot vált ki belőlem, gyorsan 'berobbanok', és utána lassan nyugszom le.", proxy:"A gyermek egy kisebb bosszúságra vagy akadályra a koránál erősebb dühvel, hirtelen kitöréssel reagál, könnyen frusztrálódik, és nehezen, lassan nyugszik meg utána.", g:"Barkley DESR érzelmi impulzivitás tételek: 'Quick to get angry or become upset', 'Easily frustrated', 'Lose my temper', 'Overreact emotionally'; felnőtt ADHD ED 34-70%" },
  // ASD (asd)
  { id:"asd1", c:"asd", d:"SZOC", self:"A kötetlen csevegés és a „small talk” könnyű és kellemes számomra — gond nélkül kezdek és tartok fenn hétköznapi beszélgetést.", proxy:"A gyermek könnyen és szívesen kapcsolódik be a kortársaival folyó kötetlen beszélgetésbe vagy közös játékba; magától is kezdeményez.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. AQ-50 item 11 ('I find social situations easy', fordított) és item 38 ('I am good at social chit-chat'); RAADS-R 'I often don't know how to act in social situations'; DSM-5 A1/A3 exemplárok.", rev:true },
  { id:"asd2", c:"asd", d:"NYELV", self:"Az átvitt értelmű kifejezéseket, az iróniát vagy a célzásokat gyakran szó szerint értem, ezért időbe telik vagy fárasztó kihámoznom, mit akar valójában mondani a másik ember.", proxy:"A gyermekem szó szerint értelmezi a kifejezéseket, és nehezen érti meg a viccet, az iróniát vagy a célzásokat (pl. zavarba jön egy szólástól, vagy a tényleges szándék helyett a szavak betű szerinti jelentésére reagál).", g:"RAADS-R 'I take things too literally, so I often miss what people are trying to say' és 'I have a hard time figuring out what some phrases mean'; DSM-5 merev/pragmatikai nyelvhasználat." },
  { id:"asd3", c:"asd", d:"RIT", self:"Ragaszkodom a megszokott napi és munkarutinjaimhoz; ha váratlanul meg kell változtatnom a megszokott menetet vagy útvonalat, az komoly feszültséget vagy szorongást okoz, és előre át kell gondolnom a változást.", proxy:"A gyermekem ragaszkodik a megszokott rutinokhoz, és heves felzaklatással reagál apró váratlan változásokra (pl. más útvonal hazafelé, egy elmozdított tárgy, megváltozott napirend).", g:"RAADS-R 'I get extremely upset when the way I like to do things is suddenly changed' és 'I like things to be exactly the same day after day'; AQ-50 item 2; DSM-5 B2 exemplárok." },
  { id:"asd4", c:"asd", d:"MOT", self:"Feszültség vagy izgatottság idején önkéntelen, ismétlődő mozdulataimmal nyugtatom magam (pl. a lábam rázom, az ujjaimmal mozgatok valamit, ringatózom vagy egy tárgyat pörgetek a kezemben).", proxy:"A gyermekemnél megfigyelhetők ismétlődő, önszabályozó mozgások (pl. kézlebegtetés, hintázás, pörgés, egy tárgy ismételt csavargatása), különösen amikor izgatott vagy feszült.", g:"RAADS-R 'I do certain things with my hands over and over again (like flapping, twirling...)' és 'It calms me to spin around or to rock in a chair when I'm feeling stressed'; DSM-5 B1 stimming exemplárok." },
  { id:"asd5", c:"asd", d:"SZENZ", self:"Bizonyos hangok, fények vagy a zsúfolt, nyüzsgő terek a mindennapokban annyira erősen hatnak rám, hogy fájdalmasak vagy gyorsan kimerítenek — mások ugyanezt észre sem veszik.", proxy:"A gyermekem bizonyos hangokra, fényekre vagy a zsúfolt, nyüzsgő terekre szokatlanul erősen reagál (befogja a fülét, menekül, felzaklatja) — mások ugyanezt észre sem veszik.", g:"RAADS-R szenzoros hiperreaktivitás (hang/fény/zsúfoltság)" },
  { id:"asd6", c:"asd", d:"RIT", self:"Egy-egy számomra fontos témában nagyon mélyen és intenzíven elmerülök; nehezen váltok róla, és akkor is részletesen beszélnék róla, amikor a másik embert láthatóan nem érdekli.", proxy:"A gyermekem rendkívül intenzíven és szűk fókusszal érdeklődik egy-egy téma vagy tárgy iránt (pl. listázza, gyűjti, vagy hosszan beszél róla), nehezen tudja témát váltani vagy abbahagyni.", g:"RAADS-R 'Sometimes a thought or a subject gets stuck in my mind and I have to talk about it even if no one is interested'; AQ-50 'fascinated by numbers/dates', 'I notice patterns in things all the time'; DSM-5 B3; monotropizmus (Murray et al. 2005)." },
  { id:"asd7", c:"asd", d:"FIG", self:"Nehezemre esik gyorsan átváltani egyik tevékenységről vagy feladatról a másikra, és egyszerre több dologra figyelni; ha valamibe belemerülök, nehezen tudok leállni vagy átállni valami másra.", proxy:"A gyermekem nehezen vált át egyik tevékenységről a másikra; az átmenetek (pl. játék abbahagyása, új feladatra állás) feszültséget okoznak, és nehezen oszt meg figyelmet több dolog között.", g:"AQ-50 attention switching alskála (items 2,4,10,16... — pl. 'I find it easy to do more than one thing at once', fordított); DSM-5/ASD végrehajtó funkció és átmenet-nehézség." },
  { id:"asd8", c:"asd", d:"ERZ", self:"A társas helyzetekben tudatosan figyelem és igazítom a viselkedésemet, az arckifejezésemet vagy betanult mondatokat használok, hogy 'normálisnak' tűnjek; ez a folyamatos önfigyelés kimerít és szorongóvá tesz.", proxy:"A gyermekem láthatóan erőfeszítést tesz, hogy beilleszkedjen a társai közé (pl. utánoz másokat, tanult viselkedéseket másol), és a társas helyzetek után gyakran kimerült vagy feszült.", g:"CAT-Q (Hull et al. 2019) item 11 'I practice my facial expressions and body language...', item 4 'I have developed a script to follow in social situations', item 25 'I feel like I am pretending to be normal', item 7 'I feel like I'm performing'; maszkolás/kiégés irodalom (Frontiers Psychiatry 2023)." },
  // Diszlexia (diszlexia)
  { id:"diszlexia1", c:"diszlexia", d:"TAN", self:"A munkám vagy a tanulmányaim során ismeretlen, hosszú vagy idegen eredetű szavakon megakadok, és magamban lassan, szótagolva kell kihangoztatnom őket, hogy ki tudjam olvasni.", proxy:"A gyermek nehezen olvassa össze a betűket szavakká: az ismeretlen szavakat nem tudja kihangoztatni, inkább a szókép alapján találgat.", g:"ARHQ Item 2 ('How much difficulty did you have learning to read'); Peterson & Pennington 2012 dekódolás-deficit" },
  { id:"diszlexia2", c:"diszlexia", d:"TAN", self:"Egy oldalnyi szöveg (például egy e-mail, hivatalos levél vagy könyvoldal) elolvasása tovább tart nekem, mint a környezetemben élőknek; lassan, akadozva haladok az olvasással.", proxy:"A gyermek a kortársainál jóval lassabban, akadozva olvas: egy rövid szöveg felolvasása is sokáig tart neki.", g:"Vinegrad Q4 ('Do you take longer than you should to read a page'); transzparens ortográfia: sebesség a domináns marker" },
  { id:"diszlexia3", c:"diszlexia", d:"TAN", self:"A helyesírásom a koromhoz és a végzettségemhez képest gyenge; gyakran elrontom a szavak leírását, és erősen támaszkodom az automatikus helyesírás-javításra.", proxy:"A gyermek helyesírása az életkorához képest gyenge: ugyanazt a szót többféleképpen, gyakran hangzás szerint is hibásan írja le.", g:"ARHQ Item 14 ('How would you compare your current spelling'); Vinegrad Q7 ('Is your spelling poor?')" },
  { id:"diszlexia4", c:"diszlexia", d:"ERZ", self:"Kerülöm, hogy mások előtt hangosan kelljen felolvasnom (például értekezleten, a családban vagy ügyintézéskor), mert kínosan érzem magam és szorongok tőle.", proxy:"A gyermek kerüli a hangos olvasást: nem szívesen jelentkezik felolvasni, kibújik alóla, vagy szorong, ha mások előtt kell olvasnia.", g:"Vinegrad Q3 ('Do you dislike reading aloud?'); BDA 'How hard do you find it to read aloud'; Yale olvasás-elkerülés" },
  { id:"diszlexia5", c:"diszlexia", d:"NYELV", self:"Amikor egy hosszú szót ki kell mondanom, néha összekeverem benne a hangok sorrendjét vagy felcserélem a szótagokat, és többször nekifutok, mire helyesen kimondom.", proxy:"A gyermek a hosszabb vagy összetett szavakat gyakran félrekiejti: felcseréli bennük a hangok vagy szótagok sorrendjét.", g:"Vinegrad Q11 ('difficult to get all the sounds in the right order'); fonológiai mag-deficit (Peterson & Pennington 2012)" },
  { id:"diszlexia6", c:"diszlexia", d:"NYELV", self:"Beszéd közben gyakran nem jut eszembe a megfelelő szó, pedig tudom, mit akarok mondani – 'a nyelvem hegyén van' érzésem van, ilyenkor körülírom vagy szünetekkel keresem a szót.", proxy:"A gyermeknek gyakran nem jut eszébe a megfelelő szó: körülírja a dolgokat, gyakran 'izé'-zik, vagy más, hasonló szóval helyettesíti, amit mondani akar.", g:"Yale adult ('It was on the tip of my tongue'); BDA 'difficult to find the right word to say'; szóelőhívás-zavar" },
  { id:"diszlexia7", c:"diszlexia", d:"FIG", self:"Amikor telefonon számokat vagy üzenetet kell feljegyeznem és továbbadnom, gyakran felcserélem a számjegyeket vagy pontatlanul adom át az üzenetet, ezért inkább azonnal leírom.", proxy:"A gyermek nehezen jegyzi meg és adja vissza pontosan a fejből kapott számsorokat vagy a több részből álló szóbeli üzeneteket; gyakran felcseréli a számokat vagy kihagy belőlük.", g:"Vinegrad Q10 ('take messages on the telephone and pass them on correctly') + Q13 ('numbers mixed up when you dial'); verbális munkamemória deficit" },
  { id:"diszlexia8", c:"diszlexia", d:"TAN", self:"Olvasás közben sokszor újra kell olvasnom ugyanazt a bekezdést, mert első olvasásra nem marad meg bennem, mit olvastam, és nagy erőfeszítésembe kerül kihámozni az értelmét.", proxy:"A gyermek a felolvasott történetet jól megérti, de amit magának kell elolvasnia, annak az értelme nem marad meg benne – újra meg kell néznie, mit olvasott.", g:"Vinegrad Q5 ('difficult to remember the sense of what you have read'); BDA 're-read paragraphs to understand them'; dekódolási erőfeszítés terheli a megértést" },
  // Diszkalkulia (diszkalkulia)
  { id:"diszkalkulia1", c:"diszkalkulia", d:"TAN", self:"Az alapvető számolási tényeket (például a szorzótáblát vagy egyszerű összeadásokat) sokszori gyakorlás után is nehezen idézem fel: amit ma tudok, az másnap újra idegennek tűnik.", proxy:"A gyermekem az alapvető számolási tényeket (például a szorzótáblát vagy egyszerű összeadásokat) sok gyakorlás után is nehezen jegyzi meg és idézi fel, mintha minden alkalommal újra kellene tanulnia.", g:"Adult Dyscalculia Screener #2-4 ('know it one day but it looks unfamiliar the next day'); DSM-5 Criterion A5 (arithmetic fact retrieval)" },
  { id:"diszkalkulia2", c:"diszkalkulia", d:"TAN", self:"Amikor fejben kellene egy több lépéses számolást elvégeznem (például összeadnom néhány tételt), elveszítem a fonalat a számolás közepén, és inkább leírom oszlopba a számokat, hogy ne tévedjek el.", proxy:"A gyermekem egy több lépéses számolás közepén gyakran elveszti a fonalat, eltéved a lépések között, és menet közben más eljárásra vált.", g:"DSM-5 Criterion A5 ('gets lost in the midst of arithmetic computation and may switch procedures'); Adult Dyscalculia Screener #6 (columns instead of mental)" },
  { id:"diszkalkulia3", c:"diszkalkulia", d:"TAN", self:"A pénzügyeim számszerű kezelése nehéz nekem: a havi számláim ellenőrzése, a visszatérő kiadásaim követése vagy a pénzem egyenlegben tartása rendszeresen gondot okoz.", proxy:"A gyermekem nehezen tartja számon a pénzt: a zsebpénzével vagy egy adott összeg beosztásával, a kiadások követésével rendre elakad.", g:"Adult Dyscalculia Screener #11-13 (utility bills, balancing a checkbook, recurring expenses); DysCalculiUM (handling of money)" },
  { id:"diszkalkulia4", c:"diszkalkulia", d:"TAN", self:"A becslés számomra nehezebb, mint a pontos kiszámolás: nehezen saccolom meg előre, hogy egy bútor befér-e egy adott helyre, vagy hogy körülbelül mennyi lesz egy bevásárlás végösszege.", proxy:"A gyermekem nehezen becsül meg mennyiségeket vagy méreteket ránézésre (például hogy egy tárgy elfér-e egy dobozban, vagy körülbelül hány darab van valamiből), és inkább egyesével megszámol mindent.", g:"Adult Dyscalculia Screener #8, #17 (estimating vs. step-by-step; furniture fitting a space); DysCalculiUM (estimation of quantity)" },
  { id:"diszkalkulia5", c:"diszkalkulia", d:"TAN", self:"Az idő és a távolság összehangolása zavaró nekem: nehezen tervezem meg előre, mennyi ideig tart egy út, vagy mikor kell elindulnom, hogy időben odaérjek.", proxy:"A gyermekem nehezen méri fel az időt: nehezen becsüli meg, mennyi ideig tart egy tevékenység, vagy mennyi idő van még hátra valamiből.", g:"Adult Dyscalculia Screener #9 ('using speed and distance to prepare travel plans is confusing'); DysCalculiUM (handling of time)" },
  { id:"diszkalkulia6", c:"diszkalkulia", d:"TAN", self:"Amikor egy számsort (például telefonszámot, számlaszámot vagy bankkártyaszámot) felolvasok, lemásolok vagy beírok, gyakran felcserélek vagy kihagyok egy-egy számjegyet anélkül, hogy észrevenném.", proxy:"A gyermekem egy számsor másolásakor vagy felmondásakor gyakran felcserél vagy kihagy számjegyeket, illetve a hasonló alakú vagy hangzású számokat összekeveri.", g:"Adult Dyscalculia Screener #15 ('I substitute or drop a number often'); idézet-bank #21 (number substitution, mixing up similar numbers)" },
  { id:"diszkalkulia7", c:"diszkalkulia", d:"TAN", self:"A törtek, százalékok és tizedes számok összevetése és gyakorlati alkalmazása nehéz nekem: például egy kedvezmény tényleges összegének vagy egy recept arányos átszámolásának kiszámítása rendszeresen elakaszt.", proxy:"A gyermekem nehezen érti meg és veti össze a törteket, a 'nagyobb mint' / 'kisebb mint' viszonyokat és az arányokat, és nehezen alkalmazza ezeket konkrét helyzetekben.", g:"Adult Dyscalculia Screener #7 ('comparing and applying fractions, percents, and decimals'); DysCalculiUM (understanding of fractions); idézet-bank #14 (comparative language)" },
  { id:"diszkalkulia8", c:"diszkalkulia", d:"ERZ", self:"Bármilyen számolás elvégzése feszültté vagy idegessé tesz: ha mások előtt kellene számolnom (például egy közös számlát elosztani), inkább másra hagyom, mert félek, hogy elrontom.", proxy:"A gyermekem szorong, feszült vagy elkerülő lesz, amikor számolnia kell: matematikai feladat vagy pénzzel kapcsolatos helyzet láttán visszahúzódik, ideges lesz, vagy másra hárítja.", g:"AMAS (Hopko et al., 2003) — math anxiety; Adult Dyscalculia Screener #5, #12 ('makes me nervous', 'leave it to someone else because I'm nervous I'll get it wrong'); Cleveland Clinic (emotional symptoms)" },
  // Diszgráfia (diszgrafia)
  { id:"diszgrafia1", c:"diszgrafia", d:"TAN", self:"A kézzel írt jegyzeteimet vagy listáimat gyakran én magam sem tudom utólag elolvasni, mert a saját kézírásom annyira nehezen kibetűzhető.", proxy:"A gyermek kézírása sokszor olvashatatlan vagy csak nehezen kibetűzhető, néha még ő maga sem tudja visszaolvasni, amit leírt.", g:"HPSQ-C legibility faktor (Item 1: \"Is the child's handwriting readable?\"); Chung 2020 \"illegible handwriting\"" },
  { id:"diszgrafia2", c:"diszgrafia", d:"MOT", self:"Már rövid ideig tartó kézzel írás után is elfárad, elgörcsöl vagy megfájdul a kezem és a csuklóm, ezért meg kell szakítanom az írást.", proxy:"A gyermek írás közben hamar elfárad, panaszkodik, hogy fáj vagy zsibbad a keze, megrázza a kezét, vagy görcsösen szorítja a ceruzát.", g:"HPSQ well-being faktor (Item 7 pain, Item 8 fatigue; \"Does the child tire while writing?\"); Danna 2022 \"pain and fatigue while writing\"" },
  { id:"diszgrafia3", c:"diszgrafia", d:"TAN", self:"Sok helyesírási hibát vétek kézzel írva, és előfordul, hogy ugyanazt a szót egyetlen szövegen belül többféleképpen, következetlenül írom le.", proxy:"A gyermek sok helyesírási hibát ejt, és ugyanazt a szót egy lapon belül is többféleképpen írja le, mintha nem tudná összekötni a hangokat a betűkkel.", g:"ARQ \"How good is your spelling?\"; DDS IV \"spelling a sentence\"; DSM-5 spelling accuracy; \"inconsistent spelling of the same words\"" },
  { id:"diszgrafia4", c:"diszgrafia", d:"MOT", self:"Amikor vonal nélküli lapra írok, a soraim hullámzanak vagy lejtenek, a betűim mérete és a szóközök pedig egyenetlenek, össze-vissza méretűek lesznek.", proxy:"A gyermek nehezen tartja a sort íráskor, a betűi egyenetlen méretűek, a szóközök hol túl szorosak, hol túl tágak, az írás rendezetlen a lapon.", g:"DDS IV \"respecting lines, spacing between words\"; Frontiers 2015 \"inconsistent letter size, uneven writing\"" },
  { id:"diszgrafia5", c:"diszgrafia", d:"NYELV", self:"Nehezen tudom a gondolataimat írásban rendezetten, érthető sorrendben papírra vetni, ezért egy hosszabb levél vagy szöveg megírása aránytalanul sok időt és erőfeszítést kíván tőlem.", proxy:"A gyermeknek nehezére esik a gondolatait írásban rendezetten, logikus sorrendben megfogalmazni, a fogalmazásai kuszák vagy hiányosan strukturáltak.", g:"ARQ / Smythe & Everatt \"difficult to organise thoughts on paper\"; ICD-11 6A03.1 \"organisation and coherence of ideas in writing\"" },
  { id:"diszgrafia6", c:"diszgrafia", d:"TAN", self:"Egy témáról sokkal gazdagabban és könnyebben tudok szóban beszámolni, mint amennyit le tudok belőle írni — szóban gördülékeny vagyok, írásban viszont elakadok.", proxy:"A gyermek szóban sokkal többet és gazdagabban el tud mondani, mint amennyit le tud írni; a szóbeli válaszai jóval jobbak az írásbelieknél.", g:"Chung 2020 \"grammar/syntax problems not mirrored in speech\"; jegyzet beszéd-írás disszociáció marker" },
  { id:"diszgrafia7", c:"diszgrafia", d:"IGE", self:"Kerülöm vagy halogatom azokat a helyzeteket, ahol kézzel kell írnom (űrlap kitöltése, jegyzetelés), és ha tehetem, inkább gépelek, diktálok vagy hangfelvételt készítek helyette.", proxy:"A gyermek kerüli vagy halogatja az írásbeli feladatokat, kifogásokat keres, és láthatóan jobban szeret szóban vagy számítógépen dolgozni, mint kézzel írni.", g:"Chung 2020 preschool \"task avoidance\"; jegyzet kompenzáció (gépelés/diktálás preferencia felnőttnél)" },
  { id:"diszgrafia8", c:"diszgrafia", d:"FIG", self:"Olyan lassan írok kézzel, hogy értekezleten vagy előadáson nem bírom követni a tempót jegyzeteléssel, és lemaradok a leírandó tartalommal.", proxy:"A gyermek olyan lassan ír, hogy nem ér a tábláról való másolással vagy a diktálás követésével, és gyakran befejezetlen, hiányos marad, amit leírt.", g:"HPSQ performance time faktor (Item 9 looking at blackboard during copying); Danna 2022 \"write slowly\"" },
  // DCD (dcd)
  { id:"dcd1", c:"dcd", d:"MOT", self:"A kézügyességet vagy testi koordinációt igénylő hétköznapi feladatok (eszközhasználat, sport, egyensúly) általában könnyen mennek nekem.", proxy:"A gyermeknek a mozgást és kézügyességet igénylő feladatok (öltözködés, eszközhasználat, sport, egyensúly) általában jól, a korának megfelelően mennek.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. ADC §2/13 'bump into things, spill or break things' + §1/7 'bump into objects or people, trip over things'; DCDQ'07 #14 'bull in a china shop'", rev:true },
  { id:"dcd2", c:"dcd", d:"MOT", self:"Az új, több lépésből álló mozgásos feladatokat (például egy bútor összeszerelését vagy egy ismeretlen sportmozdulatot) sokkal lassabban és több gyakorlással tanulom meg, mint a velem egykorúak.", proxy:"A gyermek az új mozgásos készségeket (például úszás, görkorcsolyázás, biciklizés) sokkal lassabban és több gyakorlással tanulja meg, mint a vele egykorúak.", g:"DCDQ'07 #12 'learns new motor tasks… does not require more practice or time than other children'; ADC §1/3 'learning to ride a bike compared to your peers'" },
  { id:"dcd3", c:"dcd", d:"TAN", self:"Ha gyorsan kell írnom kézzel, a kézírásom rendetlenné és nehezen olvashatóvá válik, és a kezem hamar elfárad vagy begörcsöl az írás közben.", proxy:"A gyermek kézírása vagy rajza rendetlen és nehezen olvasható, lassabban ír, mint az osztálytársai, és erősen rányom a ceruzára vagy görcsösen fogja azt.", g:"ADC §2/4 'writing neatly when having to write fast', §2/16 'others find it difficult to read your writing'; DCDQ'07 #7,#8,#9 'fast enough… legible… appropriate effort or tension'" },
  { id:"dcd4", c:"dcd", d:"MOT", self:"Az önellátó finommotoros teendők (például gombolás, cipőfűzés megkötése, borotválkozás vagy smink, evőeszköz használata) lassabban és ügyetlenebbül mennek nálam, mint másoknál.", proxy:"A gyermeknek nehézséget okoznak az önellátó finommotoros teendők (cipőfűzés megkötése, gombolás, cipzár, fogmosás, kés-villa használat), és lassabban végzi őket, mint a kortársai.", g:"ADC §2/1 'shaving or make up', §2/2 'knife and fork', §1/1 'tying shoelaces, fastening buttons and zips'; DCDQ'07 #13 'quick and competent in… tying shoes, dressing'" },
  { id:"dcd5", c:"dcd", d:"SZENZ", self:"Nehezen becsülöm meg pontosan a távolságokat és a teret, ezért például parkoláskor, szűk helyen áthaladáskor vagy vezetés közben gyakran tévedek.", proxy:"A gyermek nehezen méri fel a távolságokat és a teret, ezért gyakran átnyúl a tárgyakon, alábecsüli a távolságot, vagy beleütközik dolgokba, amikor mozgásban van.", g:"ADC §2/28 'distance estimation (parking, passing through objects)', §2/22 'difficulty parking a car'; StatPearls — adults estimating distances when driving/crossing" },
  { id:"dcd6", c:"dcd", d:"MOT", self:"Nehezen tudok két dolgot egyszerre csinálni, amihez mozgás és figyelem is kell (például vezetés közben beszélgetni vagy telefonon üzenetet jegyzetelni); ilyenkor az egyik feladat menthetetlenül kárt vall.", proxy:"A gyermeknek nehezére esik egyszerre két dologra figyelni, ha az egyik mozgásos feladat (például menet közben beszélgetni vagy labdát passzolni és közben figyelni a társakra).", g:"ADC §2/27 'performing two things at the same time (e.g. driving and listening or taking a telephone message)'; DSM-5-TR Criterion A motor automaticity deficit" },
  { id:"dcd7", c:"dcd", d:"FIG", self:"Mások gyakran dezorganizáltnak tartanak: elhagyom a holmijaimat, nehezen találom meg a dolgaimat a saját teremben, és nehézséget okoz előre megterveznem a feladataimat.", proxy:"A gyermek rendetlen és dezorganizált: gyakran elhagyja vagy nem találja a holmijait a saját szobájában, és nehezen pakol be vagy szervezi meg időben a teendőit.", g:"ADC §2/8 'organising/finding things in your room', §2/10 'others called you disorganised', §2/29 'difficulty planning ahead'" },
  { id:"dcd8", c:"dcd", d:"ERZ", self:"Kerülöm vagy szorongok az olyan szabadidős és sportos tevékenységektől, amelyek jó testi koordinációt igényelnek, mert tartok attól, hogy ügyetlennek bizonyulok.", proxy:"A gyermek nem érdeklődik a jó koordinációt igénylő sportok és mozgásos játékok iránt, és inkább kerüli azokat, illetve visszahúzódik a csoportos mozgásos tevékenységekből.", g:"ADC §2/17 'avoid hobbies that require good coordination', §2/19 'avoid team games/sports'; DCDQ'07 #11 'interested in and likes participating in sports'" },
  // Tourette/tic (tourette)
  { id:"tourette1", c:"tourette", d:"MOT", self:"A mindennapjaim során hirtelen, akaratlan motoros tic-mozdulatok jelennek meg nálam (például pislogás, fejrándítás, vállrángás vagy arcfintor), amelyeket nem szándékosan indítok el.", proxy:"A gyermekemnél otthon vagy az iskolában gyakran látok hirtelen, akaratlan motoros tic-mozdulatokat, például ismétlődő pislogást, fejrándítást vagy vállrángást, amelyeknek nincs külső oka.", g:"ATQ motoros tic-kategóriák (eye blinking, head jerk, shoulder shrugs); YGTSS motoros tic tengely" },
  { id:"tourette2", c:"tourette", d:"NYELV", self:"A mindennapjaim során akaratlan hangadó (vokális) tic-eket produkálok, például torokköszörülést, szipogást, krákogást vagy önkéntelen hangok, szótagok kiadását, amelyek nem megfázás vagy szándékos beszéd miatt vannak.", proxy:"A gyermekemnél visszatérően hallok akaratlan hangadó tic-eket, például torokköszörülést, szipogást, krákogást vagy önkéntelen hangok kiadását, amelyek nem megfázás miatt jelennek meg.", g:"ATQ vokális tic-kategóriák (grunting, sniffing, throat clearing); a vokális tic diagnosztikai specifikussága (Robertson PMC3000195)" },
  { id:"tourette3", c:"tourette", d:"SZENZ", self:"Ha vannak ilyen akaratlan mozdulataim vagy hangadásaim, előttük kellemetlen testi feszültséget, nyomást, bizsergést vagy „viszketés-szerű\" ingert érzek, amelyet a tic kivitelezése átmenetileg megkönnyebbít.", proxy:"A gyermekem arról számol be, hogy a tic-jei előtt kellemetlen belső feszültséget, nyomást vagy „viszketés-szerű\" érzést érez, amely a mozdulat vagy hang után egy időre alábbhagy.", g:"PUTS premonitorikus inger („pressure inside my brain or body\", „insides are itchy\", „after I do the tic… go away\")" },
  { id:"tourette4", c:"tourette", d:"IGE", self:"Ha vannak ilyen tic-szerű mozdulataim, rövid időre vissza tudom tartani őket (például megbeszélésen vagy nyilvános helyzetben), de ettől nő a belső feszültség, és a visszatartás után gyakran erősebben törnek ki.", proxy:"A gyermekem rövid időre vissza tudja fogni a tic-jeit (például az iskolában vagy idegenek előtt), de ettől feszültté válik, és otthon utána erősebb tic-rohamban „engedi ki\" őket.", g:"PUTS item 10 szuppresszibilitás; Robertson: partial voluntary control + rebound; Müller-Vahl: PU és szuppresszió együttjárása" },
  { id:"tourette5", c:"tourette", d:"RIT", self:"Ha vannak ilyen mozdulataim, az erősségük, gyakoriságuk és típusuk idővel hullámzik: hetek-hónapok alatt újak jelennek meg, régiek eltűnnek, és stressz, fáradtság vagy izgalom alatt felerősödnek.", proxy:"A gyermekem tic-jei időről időre változnak és hullámzanak: új mozdulatok vagy hangok jelennek meg, régiek elmúlnak, és stressz, fáradtság vagy izgalom alatt erősödnek.", g:"YGTSS/ESSTS waxing-waning („waxing and waning in frequency, intensity, number, complexity\"); befolyásoló tényezők (Robertson PMC3000195)" },
  { id:"tourette6", c:"tourette", d:"SZOC", self:"Előfordul, hogy akaratlanul megismétlem mások szavait vagy mozdulatait (echolalia/echopraxia), megismétlem a saját szavaimat, vagy ritkán illetlen szavak, gesztusok törnek ki belőlem akaratom ellenére, ami társas helyzetekben kínos.", proxy:"A gyermekemnél előfordul, hogy akaratlanul megismétel mások által mondott szavakat vagy mozdulatokat, ismétli a saját szavait, vagy ritkán illetlen szó, gesztus tör ki belőle, ami a kortársak körében problémát okoz.", g:"Müller-Vahl komplex tic-felsorolás (echolalia, echopraxia, palilalia, coprolalia, copropraxia); ATQ echopraxia/copropraxia/echolalia/coprolalia kategóriák" },
  { id:"tourette7", c:"tourette", d:"IMP", self:"Ha vannak ilyen akaratlan mozdulataim, egyesek önsértőek lehetnek: önkéntelenül megütöm, megharapom vagy megkarmolom magam, vagy nagy erővel rángatok egy testrészt.", proxy:"A gyermekemnél vannak önsértő tic-ek: önkéntelenül megüti, megharapja vagy megkarmolja magát, esetleg nagy erővel rángat egy testrészt, amitől néha fizikai sérülése, nyoma keletkezik.", g:"Müller-Vahl: önsértő viselkedés (SIB) a komplex motoros tic-ekhez és coprophenomenához kötődik (n=1032); ATQ forceful intensity anchor" },
  { id:"tourette8", c:"tourette", d:"ERZ", self:"Időnként hirtelen, az adott helyzethez képest aránytalanul heves düh-kitöréseim vannak, amelyek szinte a semmiből robbannak ki, és utólag bűntudatot érzek miattuk.", proxy:"A gyermekemnél hirtelen, a kiváltó okhoz képest aránytalanul heves düh-kitörések jelennek meg, amelyek szinte a semmiből robbannak ki, és utána a gyermek megbánást mutat.", g:"RAQ-R (Rage Attack Questionnaire-Revised, felnőtt TS); Müller-Vahl: rage attacks ~58% komorbid jegy" },
  // OCD (ocd)
  { id:"ocd1", c:"ocd", d:"RIT", self:"Ha egy kellemetlen, tolakodó gondolat felbukkan a fejemben, könnyen elengedem, és nem érzek késztetést, hogy bármilyen cselekvéssel „semlegesítsem” vagy helyrehozzam.", proxy:"Ha a gyermeket megijeszti egy gondolat, viszonylag könnyen túllép rajta, és nem érez késztetést ismételt cselekvésekre (ellenőrzés, mosakodás, rendezgetés) emiatt.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. OCI-R #11 \"I sometimes have to wash or clean myself simply because I feel contaminated\" + #17 (Washing alskála)", rev:true },
  { id:"ocd2", c:"ocd", d:"RIT", self:"A mindennapokban ismételten vissza kell ellenőriznem a zárakat, a gáz- és vízcsapokat vagy a villanykapcsolókat, még akkor is, ha tudom, hogy már elzártam vagy lekapcsoltam őket.", proxy:"A gyermek indulás vagy lefekvés előtt ismételten visszamegy ellenőrizni dolgokat (pl. táska, ajtó, lámpa), és nem nyugszik meg attól, hogy egyszer már megnézte.", g:"OCI-R #14 \"I repeatedly check gas and water taps and light switches\" + #8 (Checking alskála); Y-BOCS \"Checking locks, stove, appliances\"" },
  { id:"ocd3", c:"ocd", d:"RIT", self:"Feszültté vagy ingerültté válok, ha a tárgyaim (pl. az íróasztalomon vagy a polcomon) nincsenek pontosan a megszokott rendben, és igazgatnom kell őket, amíg \"pont jónak\" nem érződnek.", proxy:"A gyermek felzaklatja magát, ha a játékai vagy holmijai nincsenek pontos rendben vagy szimmetriában, és újra meg újra elrendezi őket, amíg \"jó\" nem lesz.", g:"OCI-R #3 \"I get upset if objects are not arranged properly\" + #9 (Ordering); IOCDF \"just right\" incompleteness" },
  { id:"ocd4", c:"ocd", d:"ERZ", self:"Gyakran törnek rám akaratom ellenére kellemetlen, nemkívánt gondolatok vagy képek, amelyeket nehezen tudok kiverni a fejemből.", proxy:"A gyermeket akarata ellenére visszatérő, kellemetlen gondolatok zaklatják fel (pl. \"rossz\" gondolatok miatt sír vagy szorong), amelyektől nehezen szabadul.", g:"OCI-R #12 \"I am upset by unpleasant thoughts that come into my mind against my will\" + #18 (Obsessing alskála)" },
  { id:"ocd5", c:"ocd", d:"RIT", self:"Amikor szorongok vagy egy szám „rossznak” tűnik, kényszert érzek, hogy fejben számoljak, bizonyos számokat ismételgessek, vagy „jó” és „rossz” számokat különböztessek meg, mert ez megnyugtat vagy bajt hárít el.", proxy:"A gyermek kényszeresen számol, bizonyos számokat ismételget, vagy „szerencse-” és „balszerencse-számokhoz” ragaszkodik, mintha ezzel bajt hárítana el.", g:"OCI-R #4 mentális számolás-kényszer" },
  { id:"ocd6", c:"ocd", d:"RIT", self:"Egyes hétköznapi cselekvéseimet (pl. egy kapcsoló le-fel kapcsolását, ajtón való ki-be lépést) addig kell megismételnem, amíg \"pont jó\" érzésem nem lesz.", proxy:"A gyermek bizonyos hétköznapi mozdulatokat (pl. lépcsőn fel-le lépés, ajtón ki-be lépés) addig ismétel, amíg \"jónak\" nem érzi, és nem tud továbblépni anélkül.", g:"Y-BOCS REPEATING RITUALS \"Need to repeat routine activities (eg, in / out door, up / down from chair)\"; IOCDF just right" },
  { id:"ocd7", c:"ocd", d:"ERZ", self:"Ismételten megerősítést keresek a körülöttem lévőktől (pl. \"biztos, hogy bezártam?\", \"biztos nem hibáztam?\"), hogy átmenetileg csökkentsem a szorongásomat.", proxy:"A gyermek újra meg újra ugyanazt kérdezi a szülőtől megnyugtatásért (pl. \"biztos rendben van?\"), és a szülőt is bevonja a rituáléiba.", g:"Y-BOCS \"Need to tell, ask, or confess\"; reassurance-seeking lit. (PMC7339499); family accommodation" },
  { id:"ocd8", c:"ocd", d:"IGE", self:"Kerülök bizonyos helyeket, tárgyakat vagy helyzeteket a mindennapjaimban, hogy elkerüljem a betolakodó gondolatok vagy a kényszeres rituálék beindulását.", proxy:"A gyermek elkerül bizonyos tárgyakat, helyeket vagy helyzeteket (\"nem nyúl hozzá\", nem megy be), hogy a szorongató gondolat vagy a kényszeres rituálé el se induljon.", g:"Y-BOCS avoidance / measures to prevent contact; OCI-R #13 elkerülő logika (\"I avoid throwing things away...\")" },
  // SPD (spd)
  { id:"spd1", c:"spd", d:"SZENZ", self:"A ruházat bizonyos textúrái (szúrós címke, durva varrás, szoros anyag) annyira zavarják a bőrömet, hogy kerülöm vagy átalakítom ezeket a ruhákat (pl. kivágom a címkét), még akkor is, ha egyébként megfelelőek lennének.", proxy:"A gyermek hevesen tiltakozik bizonyos ruhák felvétele ellen, vagy folyamatosan a varrást, címkét igazgatja, mert a ruha textúrája zavarja a bőrét.", g:"GSQ #22 ('Do you cut the labels out of your clothes?') és #1 (taktilis hiperszenzitivitás, ruha-textúra); AASP Sensation Avoiding/Touch kvadráns" },
  { id:"spd2", c:"spd", d:"SZENZ", self:"A legtöbb hétköznapi hangot, fényt és anyagot ugyanúgy, különösebb zavar nélkül viselem, mint a körülöttem lévők.", proxy:"A gyermek a hétköznapi szenzoros ingereket (hangok, fények, anyagok) különösebb zavar nélkül viseli, hasonlóan a kortársaihoz.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. GSQ #25/#6/#31 (hallási hiperszenzitivitás, 'react very strongly when you hear an unexpected sound'); AASP Auditory/Sensory Sensitivity", rev:true },
  { id:"spd3", c:"spd", d:"SZENZ", self:"Az erős fény és a vizuálisan zsúfolt, villódzó környezet (éles világítás, kijelzők, túl sok inger egyszerre) fárasztja a szememet vagy fejfájást okoz, ezért tompítom a fényt vagy kerülöm ezeket a helyzeteket.", proxy:"A gyermek hunyorog, eltakarja a szemét vagy elfordul erős, illetve villódzó fényben, és kerüli a vizuálisan zsúfolt, túl ingergazdag helyeket.", g:"GSQ #8 ('Do bright lights ever hurt your eyes/cause a headache?'); AASP Visual/Sensory Sensitivity" },
  { id:"spd4", c:"spd", d:"SZENZ", self:"Az erős szagok vagy bizonyos ételek íze/állaga annyira zavarnak, hogy kerülöm a parfümös/erős szagú helyeket, és csak egy szűk, megszokott ételkört eszem szívesen.", proxy:"A gyermek öklendezik vagy elutasít bizonyos ételeket azok szaga, íze vagy állaga miatt, és nagyon szűk, válogatós étkezési repertoárral rendelkezik.", g:"GSQ #21 (erős szagú bolt kerülése) és #23 ('hate the feel or texture of certain foods in your mouth'); AASP Taste/Smell, Sensation Avoiding" },
  { id:"spd5", c:"spd", d:"SZENZ", self:"Gyakran későn vagy egyáltalán nem veszem észre a testemet érő jeleket — például hogy megsérültem, hogy a tárgy túl forró/hideg, vagy hogy fázom —, így mások hamarabb észreveszik ezeket, mint én.", proxy:"A gyermek mintha nem érzékelné a fájdalmat, a hőt vagy a hideget (nem veszi észre a sérülését, kabát nélkül megy ki hidegben), és lassan vagy alig reagál a testét érő ingerekre.", g:"GSQ #16 ('notice that you have hurt yourself but did not feel any pain') és #39 (hidegre alul-reaktivitás); SUR / Low Registration (AASP); SPQ hipo-detektálás" },
  { id:"spd6", c:"spd", d:"SZENZ", self:"Nehezen ismerem fel időben a testem belső jelzéseit (éhség, szomjúság, fáradtság, telítettség, WC-inger), ezért gyakran kihagyok étkezést, nem iszom eleget, vagy túl későn pihenek le.", proxy:"A gyermek nem jelzi időben az éhséget, szomjúságot, fáradtságot vagy a WC-igényt, ezért az étkezés, a folyadékbevitel vagy a mosdóhasználat szabályozása nehézkes számára.", g:"GSQ #29 ('unaware of your body's signals — don't often feel hungry/tired/thirsty'); interoceptív alul-reaktivitás (Mulligan 2021, jegyzet)" },
  { id:"spd7", c:"spd", d:"SZENZ", self:"Megnyugtatónak találom az erős, mély nyomóérzetet vagy intenzív mozgást — például a súlyozott takarót, a szoros ölelést, vagy ha fészkelődöm/mozgok —, és kifejezetten keresem ezeket az ingereket, hogy összeszedettebbnek érezzem magam.", proxy:"A gyermek aktívan keresi az erős szenzoros ingereket: szoros ölelést, súlyozott takarót, nekiütközik tárgyaknak/embereknek, vagy folyamatosan mozog, pörög, hogy jobban érezze magát.", g:"GSQ #41 (testhatár-erősítő nyomás keresése) és #35/#34 (orális/mozgásos ingerkeresés); AASP Sensation Seeking; Child Mind 'deep pressure / crashing'" },
  { id:"spd8", c:"spd", d:"MOT", self:"Ügyetlenebb vagyok a finommozgást vagy testkoordinációt igénylő hétköznapi feladatokban (apró tárgyak kezelése, kézírás, gombolás, szerelés), és gyakran nekiütközöm tárgyaknak vagy rosszul mérem fel a testem helyét a térben.", proxy:"A gyermek esetlen, gyakran nekimegy tárgyaknak vagy elesik, töri a játékokat, és nehezen boldogul a finommozgást igénylő feladatokkal (gombolás, cipőfűzés, vágás).", g:"GSQ #3/#38 ('difficult to manipulate hands… delicate task', 'tie shoelaces or button up'); proprioceptív/dyspraxia (SBMD, STAR Institute); Child Mind proprioceptív nehézség" },
  // DLD (dld)
  { id:"dld1", c:"dld", d:"NYELV", self:"Könnyen és pontosan ki tudom fejezni magam szóban: megtalálom a megfelelő szavakat, és gördülékenyen, érthetően elmesélek egy történetet.", proxy:"A gyermek könnyen és érthetően kifejezi magát szóban: megtalálja a szavakat, és követhetően elmesél egy történetet vagy eseményt.", g:"FORDÍTOTT item (rev): magas egyetértés = alacsonyabb tünet. CC-SR/CC-A Language Structure (lexikai hozzáférés); TOAL-4 szókincs; Orrego (2023) word-finding első személyű leírás", rev:true },
  { id:"dld2", c:"dld", d:"NYELV", self:"Egy hosszabb vagy gyorsan elhangzó szóbeli utasítást nehezen tudok követni: gyakran megkérem a másikat, hogy ismételje meg, vagy inkább leírást kérek, mert szóban lemaradok a részletekről.", proxy:"A gyermekem egy hosszabb vagy többlépéses szóbeli utasítást nehezen követ: gyakran kéri az ismétlést, vagy csak a részét hajtja végre annak, amit mondtak neki.", g:"CELF/TILLS receptív nyelv; DSM-5-TR A-kritérium megértés; Orrego (2023) „what?” időnyerés" },
  { id:"dld3", c:"dld", d:"NYELV", self:"Nehéz egy történetet vagy egy aznap történt eseményt érthető, követhető sorrendben elmesélnem — a hallgató gyakran nem tudja végigkövetni, miről beszélek.", proxy:"A gyermeknek nehéz egy történetet vagy eseményt érthető, logikus sorrendben elmesélnie; a hallgató gyakran nem tudja követni, mi történt.", g:"CATALISE/DLD: elbeszélés (narratíva) szerveződésének nehézsége" },
  { id:"dld4", c:"dld", d:"NYELV", self:"Amikor egy bonyolultabb gondolatot kell megfogalmaznom, rövidebb, egyszerűbb mondatokban beszélek, mint amennyire a téma indokolná: nehéz egyetlen összetett mondatba összefűznöm több gondolatot.", proxy:"A gyermekem rövid, egyszerű mondatokban fejezi ki magát, és a koránál ritkábban fűz össze gondolatokat összetett mondatokká (pl. „mert”, „miután”, „bár”).", g:"CC-A Language Structure (szintaxis); TOAL-4 sentence combining; DLD morfoszintaxis hallmark" },
  { id:"dld5", c:"dld", d:"NYELV", self:"Amikor egy megtörtént eseményt vagy egy folyamatot kell elmesélnem, nehéz érthető sorrendben előadnom: gyakran kihagyok lépéseket vagy összekeverem a sorrendet, és a hallgató elveszti a fonalat.", proxy:"A gyermekem nehezen mesél el egy eseményt vagy történetet úgy, hogy a hallgató követni tudja: összevissza sorrendben, kihagyásokkal mondja el, és nehéz kihámozni, mi történt.", g:"Narratíva-deficit (acn-dld-review: shorter, less cohesive, poorly organized); CC-SR diskurzus-koherencia" },
  { id:"dld6", c:"dld", d:"TAN", self:"Egy hosszabb vagy hivatalos írott szöveget (pl. szerződés, hivatalos levél, hosszabb e-mail) a társaimnál lassabban és nehezebben dolgozok fel: gyakran többször el kell olvasnom, mire megértem a lényegét.", proxy:"A gyermekem az olvasott szöveg megértésével és a fogalmazással küzd: jóval lassabban és nehezebben érti meg az írott feladatokat, mint amit a többi képessége alapján várnánk.", g:"GORT-5/Nelson-Denny olvasásértés; DLD olvasászavar 50–60% komorbiditás; TILLS olvasás-írás" },
  { id:"dld7", c:"dld", d:"SZOC", self:"Egy csoportos vagy gyors tempójú beszélgetésbe nehezen kapcsolódom be: mire megfogalmaznám, amit mondani akarok, már továbbment a téma, ezért gyakran inkább csendben maradok vagy kerülöm az ilyen helyzeteket (pl. telefonálást).", proxy:"A gyermekem nehezen kapcsolódik be a beszélgetésbe, ritkán kezdeményez vagy kérdez spontán, és csoportban inkább passzív marad, mintha „távol” lenne.", g:"CC-SR/CC-A Social Engagement (passzív profil); PMC9769414 spontán kérdezés, beszélgetésben részvétel deficit" },
  { id:"dld8", c:"dld", d:"ERZ", self:"Amikor szóban kell teljesítenem (pl. megbeszélésen felszólalni, prezentálni, vagy egy félreértést szóban tisztázni), feszültté vagy szorongóvá válok, mert tartok tőle, hogy nem fogom érthetően kifejezni magam.", proxy:"A gyermekem frusztrálttá vagy szorongóvá válik a szóbeli helyzetekben (pl. felelés, beszélgetés idegenekkel), és gyakran visszahúzódik vagy elzárkózik, ha nem érti meg magát.", g:"DLD másodlagos szorongás/önbizalom-csökkenés (acn-review, dld-evidence-brief); Orrego (2023) blank stares hatása" },
  // PDA (pda)
  { id:"pda1", c:"pda", d:"IGE", self:"A hétköznapi feladatokat és kéréseket (például egy munkahelyi teendőt, egy hivatalos ügyintézést vagy egy otthoni házimunkát) gyakran akkor is halogatom vagy elutasítom, ha egyébként nem nehezek vagy akár szívesen is csinálnám őket — mintha pusztán az zavarna, hogy el VAN várva tőlem.", proxy:"A gyermek a mindennapi kéréseket és elvárásokat (például hogy pakoljon el, öltözzön fel vagy üljön asztalhoz) makacsul elkerüli vagy visszautasítja, akkor is, ha a tevékenység egyébként könnyű neki vagy korábban szívesen csinálta.", g:"EDA-QA #1 / EDA-8 #1: 'I obsessively resist and avoid ordinary demands and requests' — a PDA mag-tünete, az elkerülés maga a követelés-jelleg ellen irányul (PDA Society)." },
  { id:"pda2", c:"pda", d:"IGE", self:"Amikor valamit elvárnak tőlem (például egy határidős munkát vagy egy elintéznivalót), gyakran kifogásokkal élek — fáradtságra vagy testi rosszullétre hivatkozom, témát váltok vagy elterelem a szót —, hogy ki tudjak bújni a feladat alól.", proxy:"A gyermek egy-egy kérés elkerülésére kifogásokat keres: betegségre vagy testi képtelenségre hivatkozik (például hogy fáj a lába vagy nem tudja mozdítani a kezét), illetve eltereli a figyelmet, hogy ne kelljen teljesítenie a kérést.", g:"EDA-QA #2: 'I complain about illness or physical incapacity to avoid a request or demand'; PDA Society: distraction, giving excuses mint elkerülő stratégiák." },
  { id:"pda3", c:"pda", d:"IGE", self:"Fontos számomra, hogy én irányíthassam a helyzeteket: a közös tevékenységeknek és beszélgetéseknek lehetőleg az én feltételeim szerint kell zajlaniuk, és nehezen viselem, ha valaki más szabja meg a menetrendet vagy a tempót.", proxy:"A gyermeket erősen hajtja, hogy ő irányíthasson: átveszi a „főnök\" szerepét, megszabja, hogyan menjen egy játék vagy beszélgetés, és a közös tevékenységeknek az ő feltételei szerint kell alakulniuk.", g:"EDA-QA #3 'I am driven by the need to be in charge' + #23 'I ensure any social interaction is on my own terms'." },
  { id:"pda4", c:"pda", d:"IGE", self:"Ha valamit kérnek tőlem, gyakran alkudozni kezdek vagy próbálom átírni a feltételeket (jobb időpontot, más módot, kivételt kérek), és csak akkor tudom teljesíteni a kérést, ha azt nagyon óvatosan, választást hagyva tálalják nekem — a direkt utasítás szinte azonnal ellenállást vált ki bennem.", proxy:"A gyermek a kérésekre alkudozással reagál (jobb feltételeket próbál kicsikarni, „majd később\", „inkább máskor\"), és csak akkor hajlandó együttműködni, ha a kérést gondosan, nyomás nélkül fogalmazzák meg; a határozott utasítás ellenállást vált ki belőle.", g:"EDA-QA #25 'I seek to quibble and change rules set by others' + #7 'I have difficulty complying with demands unless they are carefully presented'." },
  { id:"pda5", c:"pda", d:"ERZ", self:"Amikor erős nyomást érzek egy elvárás miatt, néha kirobbanok vagy felháborító, sokkoló módon viselkedem (felemelem a hangom, drámaian reagálok, kivonulok) — részben azért is, mert így ki tudok bújni a rám nehezedő feladat alól.", proxy:"A gyermek, ha nyomást érez egy feladat miatt, „összeomlik\" (meltdown): sikoltozik, dührohamot kap, üt vagy rúg, illetve felháborító, sokkoló viselkedéssel próbál kibújni a kérés teljesítése alól.", g:"EDA-QA #21 'I sometimes use outrageous or shocking behaviour to get out of doing something' + #13 'I will still sometimes have a meltdown if I feel pressurized'." },
  { id:"pda6", c:"pda", d:"ERZ", self:"A hangulatom egészen hirtelen képes átváltani (például szeretetteljesből dühösbe egy pillanat alatt), és apró, mások számára jelentéktelen események is nálam aránytalanul erős érzelmi reakciót — heves sírást, dühöt vagy felfokozottságot — válthatnak ki.", proxy:"A gyermek hangulata villámgyorsan változik (egy pillanat alatt vált szeretetteljesből dühösbe), és apró eseményekre is aránytalanul heves érzelmi reakciókkal felel (hirtelen sírás, vihogás vagy dühkitörés).", g:"EDA-QA #15 'I have a very rapidly changing mood' + #22 'extremely emotional responses to ... small events'; Newson 2003: mood swings, highly impetuous." },
  { id:"pda7", c:"pda", d:"SZOC", self:"Közömbös vagyok a tekintély iránt: a főnök, a hivatal vagy a hivatalos szabályok nem jelentenek számomra különösebb súlyt, és gyakran úgy érzem, hogy a másokra vonatkozó elvárások és szabályok rám nem érvényesek ugyanúgy.", proxy:"A gyermek nem érzékeli vagy közömbös a közte és a tekintélyszemélyek (szülő, tanár, rendőr) közötti különbség iránt: egyenrangúként kezeli a felnőtteket, és miközben másoknak megmondja, hogyan viselkedjenek, magára nem érzi érvényesnek ezeket a szabályokat.", g:"EDA-QA #12 'unaware or indifferent to the differences between myself and figures of authority' + #5 'tell others how they should behave, but do not feel these rules apply to me'." },
  { id:"pda8", c:"pda", d:"RIT", self:"Stresszes vagy követelő helyzetekben szívesen bújok egy felvett szerep, karakter vagy „perszóna\" mögé, illetve tárgyakon vagy egy kitalált szerepen keresztül kapcsolódom másokhoz — így könnyebben kezelem a helyzetet, mintha közvetlenül, önmagamként kellene reagálnom.", proxy:"A gyermek szívesen vesz fel szerepeket és karaktereket (a tévéből vagy a valós életből), eljátssza őket, fantáziavilágokat talál ki, és gyakran egy felvett szerepben vagy tárgyakon/játékokon keresztül lép kapcsolatba másokkal — ez az elkerülés eszköze is lehet.", g:"EDA-QA #24 'prefer to interact ... in an adopted role or communicate through props/objects' + #8/#10 role-play/fantasy (Egan 2019 Faktor 2: fantasy/role-play)." },
  // Hiperlexia (hiperlexia)
  { id:"hiperlexia1", c:"hiperlexia", d:"TAN", self:"Visszagondolva a gyerekkoromra, nagyon korán, szinte erőfeszítés nélkül és külön tanítás nélkül tanultam meg olvasni — az írott szavak \"maguktól\" összeálltak bennem.", proxy:"A gyermekem feltűnően korán, az életkorához képest jóval hamarabb és gyakorlatilag magától tanult meg olvasni, anélkül hogy szándékosan tanítottuk volna rá.", g:"ARHQ Item 2 (\"How much difficulty did you have learning to read...\") fordított pólusa + Ostrolenk 2017 2. kritérium (korai, spontán olvasás-elsajátítás)" },
  { id:"hiperlexia2", c:"hiperlexia", d:"TAN", self:"Folyékonyan, hangosan és pontosan fel tudok olvasni egy szöveget, de utána gyakran nehezen mondom el a saját szavaimmal, hogy miről szólt — a kiolvasás könnyebb, mint a megértés.", proxy:"A gyermekem folyékonyan, az életkorát meghaladó szinten olvas fel, de ha utána megkérdezem, miről szólt a szöveg, nem tudja elmondani vagy megérteni a tartalmát.", g:"Ostrolenk 2017 1. kritérium (decoding–comprehension diszkrepancia); Cleveland Clinic \"they won't yet know or understand what they're reading\"" },
  { id:"hiperlexia3", c:"hiperlexia", d:"NYELV", self:"Gyakran pontosan, hangról hangra megismétlem mások szavait, vagy filmekből, szövegekből „beidézett” kész mondatokat (scripteket) használok a saját megfogalmazásom helyett.", proxy:"A gyermek gyakran szó szerint megismétli mások szavait, vagy filmekből, könyvekből „beidézett” kész mondatokat használ (echolália, scriptelt nyelv).", g:"Hiperlexia/ASD: echolália, scriptelt nyelvhasználat" },
  { id:"hiperlexia4", c:"hiperlexia", d:"TAN", self:"Az ismerős szavakat egészben, a látványuk alapján ismerem fel, de egy új vagy ritka szót nehezen \"hangzósítok ki\" — a betűkből hangokat összerakva olvasás nehezen megy nekem.", proxy:"A gyermekem a már ismert szavakat gyorsan felismeri, de egy új, ismeretlen szónál elakad, mert nehezen rakja össze a betűkből a hangokat (gyenge fonológiai dekódolás).", g:"PMC9363706: \"advanced word reading... in tandem with low phonological awareness and letter-sound correspondence skills\"" },
  { id:"hiperlexia5", c:"hiperlexia", d:"RIT", self:"A számokat, dátumokat, feliratokat és sorozatokat szinte fáradság nélkül, pontosan megjegyzem — például könnyen felidézek rendszámokat, telefonszámokat vagy pontos időpontokat a mindennapokból.", proxy:"A gyermekem kivételesen pontosan megjegyez számokat és adatokat — például rendszámtáblákat, születési dátumokat vagy fontos számokat idéz fel hibátlanul.", g:"WebMD \"frequently remember important numbers such as license plates and birth dates\"; RAADS-R Item 70 (\"thoughts stacked... like filing cards\")" },
  { id:"hiperlexia6", c:"hiperlexia", d:"SZOC", self:"Az írott információt magamtól, mások bevonása nélkül szeretem feldolgozni, és kényelmetlen, ha közben be akarnak avatkozni vagy segíteni akarnak nekem az olvasásban.", proxy:"A gyermekem egyedül, önállóan végzi az olvasással-betűkkel kapcsolatos tevékenységeit, és nem fogadja el, ha valaki kívülről be akar avatkozni vagy segíteni próbál.", g:"Ostrolenk 2024 (PMC11170776): literacy-related activities \"by themselves\", \"did not accept external intervention\" (nem-szociális, önvezérelt jelleg)" },
  { id:"hiperlexia7", c:"hiperlexia", d:"RIT", self:"Az írott szöveg és a betűk-számok világa erősen vonz: a mindennapokban szívesebben merülök el feliratokban, listákban vagy olvasnivalóban, mint a beszélgetésben vagy a társas programokban.", proxy:"A gyermekem a könyveket, betűket és számokat (például mágnesbetűket) előnyben részesíti a többi játékkal és társas tevékenységgel szemben, és sokat foglalkozik velük, akár sorba is rendezi őket.", g:"Ostrolenk 2017 3. kritérium (erős orientáció az írott anyag felé); Healthline \"like books... more than playing with other toys\"; RAADS-R Item 13 (circumscribed interests)" },
  { id:"hiperlexia8", c:"hiperlexia", d:"SZENZ", self:"Bizonyos szavak hangzása vagy egyes magas hangok a mindennapokban kifejezetten fájdalmasak a fülemnek, és olyankor menekülnék az adott hang elől.", proxy:"A gyermekem bizonyos hangokra (például egy szó hangzására vagy magas, éles zajra) befogja a fülét, mert fizikailag fájdalmasnak vagy kibírhatatlannak éli meg azokat.", g:"RAADS-R Item 36 (\"the sound of a word or a high-pitched noise can be painful to my ears\"); WebMD szenzoros érzékenység (hiperlexia II autizmus-kontextus)" },
  // Mizofónia (mizofonia)
  { id:"mizofonia1", c:"mizofonia", d:"ERZ", self:"Bizonyos hétköznapi hangokra (például mások csámcsogására, szürcsölésére vagy a billentyűzet kopogására) azonnal aránytalanul erős dühöt vagy ingerültséget érzek, miközben a körülöttem lévők ugyanezt a hangot észre sem veszik.", proxy:"A gyermekem bizonyos hétköznapi hangokra (például a családtagok evésének, szürcsölésének hangjára) azonnal aránytalanul heves dühvel vagy ingerültséggel reagál, miközben a többieket ugyanaz a hang nem zavarja.", g:"S-Five 'Perceived emotional threat' + DVMSQ B-kritérium ('excessive, unreasonable, or out of proportion'); a düh a központi mizofóniás érzelem (Jager 2020)" },
  { id:"mizofonia2", c:"mizofonia", d:"SZENZ", self:"Mások szájával vagy testével keltett ismétlődő hangok (rágás, nyelés, torokköszörülés, szipogás) nemcsak idegesítenek, hanem erős undort, viszolygást is kiváltanak bennem.", proxy:"A gyermekemnél mások szájával keltett hangok (rágás, nyelés, szortyogás) láthatóan undort, viszolygást váltanak ki — fintorog, eltolja magát, vagy azt mondja, hogy 'undorító'.", g:"S-Five és Delphi-konszenzus (Swedo 2022): 'anger, irritation, disgust'; az undor erős diszkriminatív marker, elkülönít a phonophobiától" },
  { id:"mizofonia3", c:"mizofonia", d:"SZENZ", self:"Egy kiváltó hang hangereje nem számít: a halk, alig hallható csámcsogás vagy gépelés ugyanúgy vagy még jobban felzaklat, mint a hangos zaj — nem a hangosság, hanem maga a hang fajtája zavar.", proxy:"A gyermekemet egy kiváltó hang akkor is felzaklatja, ha az alig hallható (halk rágás, szipogás); nem a hangerő zavarja, hanem maga a hang fajtája — a hangos zajokra (porszívó, sziréna) viszont nem reagál így.", g:"DVMSQ A-kritérium ('irrespective of sound intensity or perceived loudness'); Delphi-konszenzus — kulcs a hyperacusistól való elkülönítéshez" },
  { id:"mizofonia4", c:"mizofonia", d:"ERZ", self:"Amikor egy kiváltó hangot (például valaki rágását vagy lábdobolását) nem tudom elkerülni, úgy érzem, csapdába estem és elveszítem az önkontrollomat — mintha mindjárt felrobbannék.", proxy:"Amikor a gyermekem nem tud elmenekülni egy kiváltó hang elől (például közös étkezésnél), láthatóan elveszíti az önuralmát: pánikszerűen feszült lesz, kétségbeesik, vagy dührohamban tör ki.", g:"S-Five 'I feel trapped / I feel helpless / I might explode'; A-MISO-S item 5 (kontroll) + DVMSQ D-kritérium (kontrollvesztés)" },
  { id:"mizofonia5", c:"mizofonia", d:"IMP", self:"Egy kiváltó hang (mások csámcsogása, köhögése) hallatán erős késztetést érzek, hogy rákiabáljak a hang forrására vagy elnémítsam — még ha végül vissza is fogom magam, a feszültség és az inger erős.", proxy:"A gyermekem egy kiváltó hang hallatán a hangot keltő személyre kiabál, rászól vagy felé csap, hogy hagyja abba — nehezen tartja vissza ezt a hirtelen késztetést.", g:"Schröder 2013 ('aggressive impulse to scream and yell or attack the source'); S-Five 'Outbursts'; a KÉSZTETÉS gyakori, tényleges agresszió ritka (Jager 2020)" },
  { id:"mizofonia6", c:"mizofonia", d:"RIT", self:"Rendszeresen füldugót, zajszűrő fülhallgatót vagy háttérzenét/fehér zajt használok azért, hogy a kiváltó hangokat (mások evésének, gépelésének zaját) elnyomjam vagy ne halljam meg őket.", proxy:"A gyermekem rendszeresen befogja a fülét a kezével, fülhallgatót kér, vagy hangosabb zajt (zene, tévé) kapcsoltat be, hogy ne hallja a zavaró hangokat (például a testvére evésének hangját).", g:"A-MISO-S item 6 ('using other loud sounds, such as music'); Jager 2020 megküzdés (zene 99%, füldugó 86%); DVMSQ C-kritérium (block out)" },
  { id:"mizofonia7", c:"mizofonia", d:"IGE", self:"Olyan helyzeteket, ahol kiváltó hangok várhatók (közös étkezés, nyílt iroda, tömegközlekedés, mozi), tudatosan kerülök, vagy előre úgy tervezem meg a helyemet/időpontomat, hogy ne kelljen ilyen hangokat hallgatnom.", proxy:"A gyermekem kerüli azokat a helyzeteket, ahol zavaró hangok várhatók (közös családi étkezés, ebédlő, gyerekzsúr), vagy nem hajlandó az asztalnál maradni, ha mások esznek.", g:"A-MISO-S item 6 + DVMSQ C-kritérium (active avoidance); S-Five 'Impact: I avoid places'; felnőtt munka/közlekedés vs. gyermek étkezés-kontextus" },
  { id:"mizofonia8", c:"mizofonia", d:"SZENZ", self:"Nemcsak a hang, hanem bizonyos ismétlődő mozgások puszta LÁTVÁNYA (valaki lábát rázza, rágó szája mozog) is felzaklat, akkor is, ha közben semmilyen hangot nem hallok.", proxy:"A gyermekemet bizonyos ismétlődő mozgások látványa is ingerültté teszi (valaki rázza a lábát, mozog a rágó szája) — akkor is reagál, ha nem hallja a hozzá tartozó hangot.", g:"Jager 2020 vizuális trigger (68%) — misokinézia; Swedo 2022 ('stimuli associated with such sounds'); erősen diszkriminatív, gyakran kihagyott jegy" },
  // Twice-exceptional (te)
  { id:"te1", c:"te", d:"TAN", self:"Bizonyos területeken egyértelműen okos és gyors vagyok, mégis máshol annyira gyengén teljesítek, hogy a környezetem inkább lustának vagy motiválatlannak lát, nem pedig nehézséggel küzdőnek.", proxy:"A gyermek nyilvánvalóan okos, mégis bizonyos területeken annyira alulteljesít, hogy a felnőttek inkább lustának vagy motiválatlannak tartják („csak nem próbálkozik”), nem pedig nehézséggel küzdőnek.", g:"2e jegyzet: tehetséges, de alulteljesítőnek/„lustának” tűnik" },
  { id:"te2", c:"te", d:"ERZ", self:"Hajlamos vagyok be sem fejezni vagy le sem adni egy feladatot, ha nem elég tökéletes — a magamtól elvárt magas szint miatt inkább elakadok, mint hogy „hibásan” engedjem ki a kezemből — és ez tartósan, nem csak egy-egy nehéz időszakban jellemző.", proxy:"A gyermek gyakran nem ad be vagy nem fejez be egy feladatot, mert „nem elég jó” — a perfekcionizmusa miatt inkább elakad, mintsem tökéletlen munkát adjon ki a kezéből.", g:"2e jegyzet: perfekcionista elakadás, nem ad be munkát" },
  { id:"te3", c:"te", d:"FIG", self:"Ugyanazon a területen az egyik nap kiemelkedően, a másik nap kudarcosan teljesítek — a teljesítményem feltűnően és kiszámíthatatlanul ingadozik.", proxy:"A gyermek ugyanazon a területen egyik nap briliánsan, másik nap kudarcosan teljesít — a teljesítménye feltűnően ingadozik.", g:"2e jegyzet: inkonzisztens teljesítmény" },
  { id:"te4", c:"te", d:"TAN", self:"Fejben gyorsan és összetetten átlátok egy problémát, de kézzelfogható formába önteni (leírni, bemutatni, leadni) aránytalanul nehéz — a tényleges tudásom jóval a látható teljesítményem felett van.", proxy:"A gyermek fejben gyorsan és okosan átlát dolgokat, de kézzelfogható formába önteni (leírni, bemutatni) alig tudja — a tudása jóval a látható teljesítménye felett van.", g:"2e jegyzet: tényleges képesség >> kézzelfogható produkció (aszinkron)" },
  { id:"te5", c:"te", d:"FIG", self:"A fejlődésem nagyon egyenetlen: bizonyos képességekben évekkel a korom vagy a társaim felett járok, másokban viszont feltűnően lemaradok.", proxy:"A gyermek fejlődése nagyon egyenetlen: egyes területeken jóval a kora felett teljesít, másokon feltűnően elmarad a társaitól.", g:"2e: aszinkron fejlődés" },
  { id:"te6", c:"te", d:"ERZ", self:"Amikor felzaklat, hogy egy egyszerűbb feladaton elakadok, miközben tudom, hogy összetettebb dolgokra is képes vagyok, sokáig nem tudok másra figyelni vagy dolgozni — a saját ki nem használt képességem és a teljesítményem közti ellentét frusztrál.", proxy:"A gyermek erősen frusztrálttá válik, amikor egy számára egyébként könnyűnek tűnő feladaton elakad, és ilyenkor sokáig nem tud megnyugodni vagy továbblépni — láthatóan zavarja, hogy okos, mégsem boldogul vele.", g:"DERS-18 (\"When I'm upset, I have difficulty getting work done / focusing on other things\") + Beckmann & Minnaert (2018) diszkrepancia-frusztráció mint a 2e leggyakoribb nem-kognitív jegye" },
  { id:"te7", c:"te", d:"ERZ", self:"Sokáig sem a tehetségem, sem a nehézségem nem tűnt fel igazán, mert a kettő kioltotta egymást: az átlagosnak látszó összkép elfedte, hogy egyes részterületeken kiemelkedő, másokon elmaradó vagyok.", proxy:"A gyermeknél sokáig sem a tehetség, sem a nehézség nem tűnik fel, mert a kettő kioltja egymást: az átlagos osztályzatok elfedik, hogy egyes területeken kivételes, másokon elmaradó.", g:"2e: kölcsönös maszkolás / aluldiagnosztizálás" },
  { id:"te8", c:"te", d:"FIG", self:"Ahhoz, hogy a gyengébb területeimen (pl. szervezés, írásbeli adminisztráció, rutinügyek) lépést tartsak, olyan sok rejtett erőfeszítést és saját kitalált trükköt kell bevetnem, hogy kívülről nem látszik a nehézség, belül viszont kimerít.", proxy:"A gyermek a gyengébb területeit (pl. olvasás, írás, szervezés) saját kitalált fogásokkal annyira ügyesen leplezi, hogy a nehézség kívülről alig látszik, viszont az állandó pótlás láthatóan kifárasztja.", g:"Rizzo et al. (2025) kompenzáció/maszkolás + Beckmann & Minnaert (2018) \"using compensatory techniques\"; Zamora (Child Mind): kompenzáció miatt \"go under the radar\"" },
];

/* Likert-skála (0–4) */
const SCALE = [
  { v:0, label:"Egyáltalán nem" },
  { v:1, label:"Inkább nem" },
  { v:2, label:"Néha / részben" },
  { v:3, label:"Gyakran" },
  { v:4, label:"Teljesen jellemző" },
];

/* Kombináció- / komorbiditás-szabályok (mindkét/mindegyik tag emelkedett = jelzés) */
const COMBO_RULES = [
  { when:["adhd","asd"],                          min:50, title:"Lehetséges AuDHD-profil",
    text:"Az ADHD- és az autizmus-profil egyszerre emelkedett. A kettő gyakran együtt jár (AuDHD), tünettani átfedéssel — az elkülönítés szakemberi értékelést igényel." },
  { when:["tourette","ocd"],                      min:50, title:"Tic + kényszeresség együtt",
    text:"A Tourette/tic és az OCD ismert komorbiditás; a premonitórikus inger (tic) és az obszesszív szorongás (OCD) elkülönítése fontos." },
  { when:["tourette","ocd","adhd"],               min:50, title:"TS–OCD–ADHD triász",
    text:"A Tourette gyakran ADHD-val és OCD-vel együtt jelenik meg — ez a klasszikus hármas mintázat." },
  { when:["diszlexia","diszgrafia","diszkalkulia"],min:45, title:"Halmozott tanulási nehézség",
    text:"Több specifikus tanulási terület (olvasás, írás, számolás) egyszerre emelkedett — ezek gyakran együtt fordulnak elő." },
  { when:["asd","spd"],                           min:50, title:"Autizmus + szenzoros profil",
    text:"Az autizmus- és a szenzoros profil együtt magas; a szenzoros érzékenység az autizmus gyakori, jól dokumentált kísérője." },
  { when:["asd","pda"],                           min:45, title:"PDA az autizmus-profil részeként",
    text:"A PDA leginkább az autizmus-spektrumon belül értelmezhető mintázat; a kettő együttes emelkedése ezt tükrözi." },
  { when:["asd","hiperlexia"],                    min:45, title:"Hiperlexia + autizmus",
    text:"A hiperlexia jellemzően autizmushoz társul (korai olvasás a szövegértés elmaradása mellett)." },
  { when:["mizofonia","spd"],                     min:45, title:"Mizofónia + szenzoros háttér",
    text:"A mizofónia és a tágabb szenzoros érzékenység könnyen összemosódik; a hangérzékenység hátterét érdemes szakemberrel feltárni." },
  { when:["te","adhd"],                           min:45, title:"Tehetség + figyelmi eltérés (2e)",
    text:"A magas képesség és az ADHD-jellegű figyelmi mintázat együtt kétszeresen kivételes (2e) profilt sejtet — a kettő kölcsönösen elfedheti egymást." },
];

/* Nehezen elkülöníthető párok — figyelmeztető szövegek (mindkettő emelkedett) */
const DIFF_PAIRS = [
  { a:"adhd", b:"asd",        text:"ADHD ↔ Autizmus: erős a tünet-átfedés (végrehajtó funkció, szenzoros érzékenység). Az autizmusnál a repetitív viselkedés és a szociális kommunikáció eltérése a kulcs, az ADHD-nál az impulzivitás — az elkülönítés szakembert igényel." },
  { a:"asd",  b:"pda",        text:"Autizmus ↔ PDA: a PDA az elvárások szorongás-vezérelt elkerülésében és a megőrzött szerepjáték-/szociális felszínben tér el — vitatott konstruktum, óvatosan értelmezendő." },
  { a:"ocd",  b:"asd",        text:"OCD ↔ Autizmus: az OCD-rituálé szorongáscsökkentő és a személy számára kellemetlen (ego-disztón), az autista repetíció gyakran megnyugtató, kívánt (ego-szintón) — ez a fő elkülönítő." },
  { a:"mizofonia", b:"spd",   text:"Mizofónia ↔ Szenzoros: a mizofónia specifikus (gyakran emberi) hangforráshoz kötött düh-reakció, a szélesebb szenzoros érzékenység hangerő-vezérelt és forrástól független." },
  { a:"diszlexia", b:"dld",   text:"Diszlexia ↔ Nyelvi zavar (DLD): a diszlexia elsősorban az írott szó dekódolását érinti, a DLD a beszélt nyelv egészét (szókincs, grammatika, megértés) — gyakran együtt is járnak." },
];
